### ISSUE TITLE
Random crashes when switching videos

### ISSUE THREAD

**Issue by garymohan** [SuperrSonic/WiiMC-SSLC#26]
Random crashes when switching videos.  Having previously watched a video for a long time seems to be a factor, possibly pointing to a memory leak.

Had been running it overclocked on a Wii U.

**Comment by SuperrSonic** [comment]
Can you confirm this happens on standard WiiMC? What format is the container? I have experienced memleaks, but not consistently. Usually if I stick to MKV with no attachments, free mem stays the same.

You can check current mem by setting debug=4 in settings.xml and bringing up the OSD during a video, note that if you switch to standard WiiMC your settings will reset. If the mem1 display is stuck, it's run out, and performance will be lower.

**Comment by garymohan** [comment]
Am using M4V.

**Comment by pirostudio-at-github** [comment]
Hello, I'm experimenting several crashes also, mostly when having a external DVD player plugged in. It may read the DVD once and then, the hardware stay busy, never stop. When ejecting and changing disk exeception occured.
WiiMC classic doesn't recognise my external DVD player.
Any way, how can I edit the settings.xml, to have logs. Where do we retreive logs.

**Comment by SuperrSonic** [comment]
There's no logging exposed in wiimc, if you want me to have a better chance of fixing something I need to be able to reproduce it, or at least send the code dump.

I don't have an external dvd player but since it's connected by usb, you could try using the alternate usb module.
https://github.com/SuperrSonic/WiiMC-SSLC/blob/master/other/apps/WiiMC-SS/meta.xml#L27
Remove the arrows to enable the argument.
You must have IOS 202 installed (the one used by WiiMC before IOS 58 was available.) There is a copy here but only as a backup, it hasn't been tested, so I can't truly recommend it, beware.

**Comment by pirostudio-at-github** [comment]
I can see that I'm not familiar enough with the procedure on wii, I will begin to move to OS 202, of check if it's the case, because I think I've installed three different version of OS.
For the code dump, (or you meant core dump ?) I don't know where to retrieve it, but I can share if a would.
Do you test on a virtual environment for debug ?
