### ISSUE TITLE
Online media takes me to radio stations

### ISSUE THREAD

**Issue by Everythintechyt** [SuperrSonic/WiiMC-SSLC#27]
Hello so if I don't have original WiiMC installed if I go to the online media category it will take me to radio stations

**Comment by SuperrSonic** [comment]
Fixed in the latest changes, this was supposed to be an advanced option where users could specify a url as an argument that would allow them to update their links from their phones/tabs/etc, it never got anywhere, but after some panic from a failing harddrive I just threw in all the changes I had been working on, which broke a bunch of stuff in the process but luckily I've managed to keep track of everything, I think.

If you want the online media section to behave like normal, try placing the onlinemedia.xml from the original WiiMC (or the one that's here in the other/ folder) on the app's dir.

I have one more thing pending with WiiMC, once I get to that there will be a new build available.
