### ISSUE TITLE
{Suggestion} Port to wii u?

### ISSUE THREAD

**Issue by Chibi-Usa** [SuperrSonic/WiiMC-SSLC#29]
The wii u doesnt have a homebrew media centre, maybe this could be ported to the wii u?

**Comment by SuperrSonic** [comment]
I don't have experience porting, but I do know there's a lot of GX-specific work done in WiiMC, so this is a rather massive project that I can't even consider. Either way, I don't have the hardware.

**Comment by Chibi-Usa** [comment]
one last thing, do you happen to know how to add an smb share?

i for the life of me cannot figure it out

**Comment by SuperrSonic** [comment]
I'll try to list out the steps I remember.

I've only tried it with windows XP/10/11 for the latter two, one has to go to the "Turn Windows features on or off" menu and checkmark the SMB 1.0 option and turn off the removal option.

Right click a folder you want to share and modify the sharing options/permissions, here you can also set the share name, I've never bothered with setting a username and password. You may also need to find the advanced sharing settings to make sure the PC is discoverable. A reboot may be required.

On WiiMC, when adding an smb share you can now input the "share name" and IP address. The display name is only used for display, so it can be anything, but recently it's also used as the hostname but because the library used for smb support isn't fully working the ip lookup only seems to work on dolphin. If it does work, selecting "Share IP" will automatically fill the ip, but if it fails it should only fill the "base" values.

If you don't know the ip address, you can open command prompt and write ipconfig to get the ipv4 value.

**Comment by Chibi-Usa** [comment]
this works thank you

it was share name i was getting trapped on, now i can use my wii/wii u as a media player for my network content ||shame its only 720||
