### ISSUE TITLE
How are you supposed to compile the forwarder?

### ISSUE THREAD

**Issue by bladehorton** [SuperrSonic/WiiMC-SSLC#30]
I do see that in the source code files, there is a section for building the forwarder, although I cannot figure out how. The only WAD file I can find does install what looks to be a forwarder, but it just blanks out, no matter if the meta.xml file is from WiiMC, or WiiMC-SS

**Comment by SuperrSonic** [comment]
The channel installer code is from forking WiiMC, I've never used it. The wad hosted here is the forwarder channel, packed from a Wii and edited with available tools like customizemii, to change textures and the forwarder dol for fix94's version because it supports disabling ahbprot.

It shouldn't work on vWii, since it's using a very old homebrew nandloader.
