### ISSUE TITLE
[Feature Request] UPnP Support?

### ISSUE THREAD

**Issue by HeteroChromia420** [SuperrSonic/WiiMC-SSLC#35]
Title's pretty self-explanatory. Can WiiMC-SSLC support UPnP? (as that's the easiest way to share files around between two systems)

**Comment by SuperrSonic** [comment]
I'm not against it, but since there's no lib I can use straight away, I'd have to invest hours on something that can already be done with samba, ftp, or http.

I'm restricting the amount of time I spend on wii stuff since there's no satisfaction feeling anymore, and I want to focus on other projects. The only reason _issues_ are still enabled is for potential bugfixes and reasonable requests.
