### ISSUE TITLE
Increase timeout of streaming + add RiiTube to WiiMC-SS

### ISSUE THREAD

**Issue by larsenv** [SuperrSonic/WiiMC-SSLC#37]
I'm using WiiMC to do streams of YouTube, Vimeo, Dailymotion, and IPTV. You can download the onlinemedia.xml here. http://riitube.rc24.xyz/onlinemedia.xml

Could this be implemented into your version? It runs by piping yt-dlp in combination with using the API of Invidious on YouTube, and it was easy to make and works pretty decently.

A problem I have is with doing IPTV, it seems like when there's nothing downloaded for 15 seconds it times out. I will assume it's 15 seconds because of the code, but this causes our stream to quit playing then exit. Could this be remedied and changed to a different value to time out like 30 seconds?

P.S. I've wanted to talk to you for some time, but I couldn't find a Discord anywhere to contact you and you turned GBAtemp PMs off. How do you expect people to have contact with you?

Also, your apps are on https://oscwii.org/ if you're OK with that.

**Comment by SuperrSonic** [comment]
Video from http has always been problematic, I've never found a solution in years.
I don't really understand your other question. If the xml works, what is there to implement?

I don't expect wii homebrew people to contact me, plus I'm kind of done with the scene.

I'm OK with app mirrors, but I can't recommend using them since I have no control over them.

**Comment by SuperrSonic** [comment]
Since the requests are unclear, this issue is now closed.
