### ISSUE TITLE
Kokokool from the other SS links you have

### ISSUE THREAD

**Issue by Kokokool** [SuperrSonic/WiiMC-SSLC#4]
hhello, im trying to reconnect to this post written months ago where you answered.

your Quote:

Sorry just spotted this, this isn't the current WiiMC-SS repo it's https://github.com/SuperrSonic/WiiMC-SSLC

"I am aware of the issue with http streaming dropping out, it seems that if WiiMC is not frequently downloading then the connection will stop and play what it has left from the memory cache.

I added a setting you could try (by editing settings.xml) it changes the cache filling from 8MB to 2MB, which is enough for streaming, just avoid pausing the stream. The streams I've tested run all the way through."

1.- Now this is related to tv streams which in some cases there aren un m3u8 format. WiiMC manages these files opening in several "pieces" of ts files. then, when I opened any on these files it plays for about dunno 10 seconds and drops. 
2.- Cant find Settings.xml since I dont have access to the build. 
3.- i'm trying to find a way Wiimc manages m3u8 files properly.

Take care and I hope you could help me.

**Comment by SuperrSonic** [comment]
Yeah, WiiMC is just not capable of reading those .ts chunks as one stream.

I don't typically bother with streaming, however I did spend some time a while ago trying to get Toonami Aftermath working, as it had the same issue you mentioned.

I used VLC's stream option, picked the m3u8 link, and set the destination to http, mux to .flv only, and it works very well since there's no need to re-encode.

Unfortunately, the desktop version of VLC is required, I've tried to replicate this on Android without success.
