### ISSUE TITLE
Can not find a valid sd or usb error.

### ISSUE THREAD

**Issue by DigiD2** [SuperrSonic/WiiMC-SSLC#45]
Hello and sorry to bother you. I tried searching the web for days but i cant seem to find a fix for this. 
No matter which WiiMC version i use, this error keeps popping up. I have an SD setup with apps/retro games and a hdd with GC/Wii games, both fat32. 

I have tried multiple versions of WiiMC-SS and the original Wii-MC but this keeps popping up. I modded my wii with ModMii.
Ive ran into no other issues besides getting this to work. The only thing i havent tried is NTFS because i didnt want to format my sd or hdd. Any help from anyone would be appreciated. Sorry if the answer is obvious, i just couldnt find any help so far.

**Comment by SuperrSonic** [comment]
This doesn't seem to be a common issue. If your SD and USB works on the homebrew channel but not WiiMC, I'm not sure what to recommend.

WiiMC-SS does offer IOS switching, so you could try https://github.com/SuperrSonic/WiiMC-SSLC/blob/master/other/apps/WiiMC-SS/meta.xml#L27
Though you will only get usb 2.0 speed if you use the default (58) or 202 which requires an old cIOS that the WiiMC team used to offer before IOS 58 got official support.

NTFS is not currently supported by this fork and needs to be manually compiled to enable it again. I removed it because when I used it the experience was bad, and after many years FAT32 has become sort of a necessity thanks to all 3 GameCube usb loaders only supporting that. Removing the NTFS lib allows more memory to be used for decoding and lessens the problem of memory leaks.

**Comment by DigiD2** [comment]
Appreciate the help and the info,the fix was a really dumb but easy one. WiiMc is only reading usb1,not the usb closest to the edge of the console or the sd.  
I found an old usb thumb drive i had laying around and just put it into the other usb slot and now it all works. Before doing this i tried using other IOS like you suggested but none of them worked with sd or usb0.

 Messing with iptv/youtube etc and everythings fine now. Only issue is that port i was using for HID controllers is now being used for this, so maybe ill just stick to using a wii classic controller for now. 

Just happy its working and amazing work on wiimc , loving the options and features youve put into it. Had no clue that ntfs lib could even use that much memory, figured it was much simpler but i have no knowledge about these things. Thanks so much for your help and the lesson.

**Comment by SuperrSonic** [comment]
It might be easy to support port 1, especially if the homebrew channel supports it but I don't have plans to work on WiiMC for now.
