### ISSUE TITLE
Another question related to m3u scripts

### ISSUE THREAD

**Issue by Kokokool** [SuperrSonic/WiiMC-SSLC#5]
SS, I have another question regarding m3u recognition over syntaxis.

I know that extinf m3u are supported, but i cant make tvg-logo= to work properly with Wiimc. It shows the entire string. The same m3u works for other platforms.

However, if a use the other m3u structure (meaning thumb=, background=, url=, etc, it works perfect). the problem lays in theres not compatible with the other platforms i have.

Any clues? am I missing something in extinf protocol?¿ that can make it to work?

**Comment by SuperrSonic** [comment]
Is that part of the format? It might be something new, because it doesn't exist in the source: https://github.com/dborth/wiimc/blob/master/source/mplayer/playtreeparser.c#L465

At least for m3u files it just looks for the title and link. For artwork I've only been able to specify it if it's a link stored in the onlinemedia.xml file, with the image="" tag.

Are you specifically trying to get the links to work, or it works but you can't get the artwork to show up?

**Comment by Kokokool** [comment]
the Second. 

LEt me summarize: 

I have a very huge streaming system runnig on wiimc. 
Also I have the same streaming system for smart tv's and android/iphones.

Pastebin is mainly with extinf format. thus name after comma, and then the link. this format works surprinsingly well in all devices. The problem lays in trying to expand this by adding tvg-logo"" tag. So, when I added a tvg-logo attribute and save my pastebin, it works on all devices (is shows the picture and the title very good, except Wiimc which shows the entire logo (suposing that is not detected as an attribute). 

In parallel, i manage to get this thing to work by using another playlist code, something like this:


version=1
background=
title=
#
type=video
name=Bumblebee
thumb=http://reyli.000webhostapp.com/Portadas/images%20(11).jpeg
URL=http://archive.org/download/B1mbl8b91Latino/B1mbl8b91%20latino.mp4

With this format, Wiimc recognizes the picture and the link. the problem is that this format is completely incompatible with all the other devices.

So my question is... is there a way that tvg-logo="", can be recognized as an attribute?, since all the other devices recognized it as it is?

Hope you could help me on this.

Bye Diego (your name right?)

**Comment by SuperrSonic** [comment]
If you have to address me just use my user name.

As you might have realized tvg-logo is not supported, and the only playlist format with image support is .plx, I had no idea. 

It's a bit complicated to implement in m3u, because the parser is extremely simple. It looks for #EXTINF: lines and looks for the first comma to get the title.

I have implemented it like this: Get the title like normal, but also check for an equal sign. If an equal sign is found remove the first character (which would be " the first quote.) then it looks at the end (at this point it would have the title included) to remove every character until it finds ", the end quotes and comma. This gets things working, but yes, it means you must modify your links so that there is no space between tvg-logo="image.jpg",video name, i.e. ", is correct, " , is not.

This is the best I can do.

**Comment by Kokokool** [comment]
SS
yeah I see. Well, as I said, tvg-logo works very well for smart tvs, IPTV (android), movían , etc. But the same playlist in WIIMC doens´t

for instance:
tvg-logo="https://www.imdb.com/title/tt0093409/mediaviewer/rm63577088?ref_=tt_ov_i"

This link is detected in smart tv's and android/iPhone phones very good but in wiimc is detected as a laaarge string line. 

I would love to see in the future the way to add this feature in the source code. This would make a huge difference in multimedia specs and information.

**Comment by SuperrSonic** [comment]
Oh, maybe I wasn't clear enough, the next update will have it but it _must_ be within EXTINF and before the comma.

Like I said: #EXTINF: 0 tvg-logo="http:blah/blah/etc",Video Title 01

Will work fine, I am still solving some issues and once I get that done I will release it.

**Comment by Kokokool** [comment]
No no, completely understood 
Hope this gets released sooner.

Take care SS.

**Comment by SuperrSonic** [comment]
Update is out.
